name: alias
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/Erihmar1259/

environment:
  sdk: ^3.1.5
license: MIT
# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
executables:
  alias: alias
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
