name: alias_tzl
description: A command-line tool for simplifying Flutter commands with aliases.
version: 1.1.2
repository: https://github.com/Erihmar1259/alias

environment:
  sdk: ^3.1.5
license: MIT
# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
executables:
  alias_tzl: alias_tzl
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
